# Generated by Django 5.2.6 on 2025-12-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_question_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option1_image',
            field=models.ImageField(blank=True, null=True, upload_to='options/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option2_image',
            field=models.ImageField(blank=True, null=True, upload_to='options/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option3_image',
            field=models.ImageField(blank=True, null=True, upload_to='options/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option4_image',
            field=models.ImageField(blank=True, null=True, upload_to='options/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.IntegerField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
